name: Code Checks

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deno setup
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Unit tests
        run: deno task test

      - name: Format checks
        run: deno task format:check

      - name: Lint checks
        run: deno task lint:check
